export default {
  ARTICLES: 'ARTICLES',
  DOG_BIO: 'DOG_BIO',
  GIT_ACTIVITY: 'GIT_ACTIVITY',
  OPEN_SOURCE: 'OPEN_SOURCE',
  PROFESSIONAL_BIO: 'PROFESSIONAL_BIO',
  PERSONAL_BIO: 'PERSONAL_BIO',
  NAVBAR: 'NAVBAR',
};
